// Copyright © 2023 Michael Thompson
// SPDX-License-Identifier: GPL-2.0-or-later

// Code generated by mk_enums.go.  DO NOT EDIT.

package vectordata

const (
	mit0 = iota
	mitLayers
	mitLayer
	mitMenuitem
	mitFeatures
	mitFeature
	mitMarker
	mitHtml
	mitPopup
	mitStyle
	mitAttestation
	mitPoint
	mitPaths
	mitPath
	mitRoute
	mitRectangle
	mitPolygon
	mitCircle
	mitRadius
	mitPixels
	mitSegment
	mitSegments
	mitConfig
	mitBaseStyle
	mitAttestationType
	mitAttSym
	mitModStyle
)

var nameToTypeMap map[string]int = map[string]int{
	"layers":      mitLayers,
	"layer":       mitLayer,
	"menuitem":    mitMenuitem,
	"features":    mitFeatures,
	"feature":     mitFeature,
	"marker":      mitMarker,
	"html":        mitHtml,
	"popup":       mitPopup,
	"style":       mitStyle,
	"attestation": mitAttestation,
	"point":       mitPoint,
	"paths":       mitPaths,
	"path":        mitPath,
	"route":       mitRoute,
	"rectangle":   mitRectangle,
	"polygon":     mitPolygon,
	"circle":      mitCircle,
	"radius":      mitRadius,
	"pixels":      mitPixels,
	"segment":     mitSegment,
	"segments":    mitSegments,
	"config":      mitConfig,
	"baseStyle":   mitBaseStyle,
	"attestationType": mitAttestationType,
	"attSym":      mitAttSym,
	"modStyle":    mitModStyle,
}

var typeMapToName []string = []string{
	"(unknown type)",
	"layers",
	"layer",
	"menuitem",
	"features",
	"feature",
	"marker",
	"html",
	"popup",
	"style",
	"attestation",
	"point",
	"paths",
	"path",
	"route",
	"rectangle",
	"polygon",
	"circle",
	"radius",
	"pixels",
	"segment",
	"segments",
	"config",
	"baseStyle",
	"attestationType",
	"attSym",
	"modStyle",
}
